### PR TITLE
fix for Bug 565487: Consider clock time for reporting duration while …

### PR DESCRIPTION
**Pull request by AshwiniChalla**
Bug 565487: Consider clock time for reporting duration while merging trx files when tests are run in parallel

### CODE REVIEW

**Comment by ericsciple** [comment]
Is this one ready to merge? We're planning for a 1.103.0 release on Monday to roll-out to the SU0 hosted image.

**Comment by ericsciple** [comment]
@AshwiniChalla ?

**Comment by vimegh** [comment]
:+1:

**Comment by kaadhina** [comment]
Looks fine to me.

**Comment by vimegh** [comment]
Ashwini is on leave. Kavipriya and I have reviewed the code. Before going on leave Ashwing confirmed to me that she had tested it for the cases that I mentioned. Merging this Pull request.

**Pull request merged**
