### PR TITLE
Add ***NO_CI***, [skip ci]", and "[ci skip]"

### PR DESCRIPTION
**Pull request by JordanEllis6809**
[issue](https://github.com/Microsoft/vsts-agent/issues/1791)

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
NO_CI is a service concern.  The agent never cancels anything.  The service sends cancel messages.

**Comment by JordanEllis6809** [comment]
Ahh interesting, it seems that VSTS Git repositories don't currently have this support though. We hit an infinite build loop when setting up CI/CD against them, and thought the this was the proper place to implement this fix.

Is there another repo for the VSTS service?

**Comment by JordanEllis6809** [comment]
There may be some confusion on my end @bryanmacfarlane, are you referring to a COM service, or the remote service?

**Comment by TingluoHuang** [comment]
@JordanEllis6809 there was a bug 2-3 weeks back that causing `***NO_CI***` not working, but the bug has been fixed already.
https://github.com/Microsoft/vsts-agent/issues/1760

**Comment by JordanEllis6809** [comment]
@TingluoHuang shoot it looks like we hit this problem around this time frame (~12 days ago), and never came across this GH issue when searching the web for others experiencing this. Thank you!

**Comment by bryanmacfarlane** [comment]
The VSTS remote "service".  It is what triggers jobs and respects NO_CI.  I believe there was a bug in that was recently fixed.  Can you try it again?

To answer your question, service issues and requests should go to dev community:
https://developercommunity.visualstudio.com/spaces/21/index.html

**Pull request closed without merging**
