### PR TITLE
Loading Release Job Extension for Deployment host type

### PR DESCRIPTION
**Pull request by KrishnaAdityaB**

### CODE REVIEW

**Comment by KrishnaAdityaB** [comment]
@TingluoHuang @patrickcarnahan @kmkumaran @niadak
Please review

**Comment by TingluoHuang** [comment]
@KrishnaAdityaB what's this change for? the JobExtension is defined as per host type.

**Comment by TingluoHuang** [comment]
Here is what i would suggest:

Create a DeploymentJobExtension.cs with
``` C#
public class DeploymentJobExtension: ReleaseJobExtension
{
    public override string HostType => "deployment";
}
```
and revert other changes.

**Comment by niadak** [comment]
+1 for Tingluo's suggestion.

**Comment by KrishnaAdityaB** [comment]
@TingluoHuang I like the suggestion. I will close this and open a new PR. Thanks.

**Pull request closed without merging**
