### PR TITLE
update to netcore app 1.1

### PR DESCRIPTION
**Pull request by TingluoHuang**

### CODE REVIEW

**Comment by superjulius** [comment]
Hope it gets reviewed/approved soon...can't wait to get 1.1 on VSTS

**Comment by bryanmacfarlane** [comment]
Hold on - this is about build with 1.1 the agent with 1.1.  I was commenting on @superjulius comment.  Assuming @superjulius is talking about 1.1 tooling on the image (and not how we build the agent)

**Comment by superjulius** [comment]
Thank you for your insights @bryanmacfarlane and sorry for the confusion as I was indeed thinking about the hosted pool image.

**Comment by bryanmacfarlane** [comment]
we will add that soon. thanks :)

**Comment by follesoe** [comment]
Any updates / issues to track to get notification on when 1.1 is available on the hosted images?

**Comment by bryanmacfarlane** [comment]
@follesoe This PR has nothing to do with 1.1 on hosted image.  This is about our agent binary building with 1.1

**Pull request merged**
