### PR TITLE
add limited support for authenticated proxies using default credentials

### PR DESCRIPTION
**Pull request by stiliev**
add limited support for authenticated proxies using default credentials, which is working only with proxies using Windows SSO.

### CODE REVIEW

**Comment by stiliev** [comment]
I verified this change does not brake Fiddler or Charles, but I don't have an auth proxy to see if it really works for the intended use case.

**Comment by bryanmacfarlane** [comment]
I think I want to take this for the next preview.  Ting/Eric, any obvious reason not to?

**Comment by ericsciple** [comment]
It hasn't been tested. And I would guess that it requires `DefaultNetworkCredentials` not `DefaultCredentials`. AFAIK, there isn't anyone with an issue ready to confirm this fix.

**Comment by bryanmacfarlane** [comment]
closing since different PR

**Pull request closed without merging**
