### PR TITLE
add timeouts in IPC communication between agent.listener and agent.worker process

### PR DESCRIPTION
**Pull request by stiliev**

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
Just a high level question - just curious, have we hit an issue with this or is this being added just in case?  What's motivating this work now?

**Comment by TingluoHuang** [comment]
@bryanmacfarlane the current logic has some bug during cancellation, like the worker will running even agent exist. :), this PR is going to fix part of the issue.

**Comment by ericsciple** [comment]
I saw these issues as well over the weekend. I added TODO comments in my branch to think through them more thoroughly (required for cancellation to be correct). I'm glad they have already been thought through! I couldn't come up with a good solution. I like the solution here.

**Comment by ericsciple** [comment]
looks good.

**Pull request merged**
