### PR TITLE
Changing to allow root to run config.sh

### PR DESCRIPTION
**Pull request by samedder**
Fixes issue #1481

### CODE REVIEW

**Comment by samedder** [comment]
@bryanmacfarlane @TingluoHuang can you check this PR?

**Comment by samedder** [comment]
@TingluoHuang / @bryanmacfarlane any update?

**Comment by bryanmacfarlane** [comment]
We ran some tests and running as a service in major configs and linux plats failed.  We talked about broader changes, but here's where my head is at ...

Keep the check there but add an override envvar AGENT_ALLOW_RUNASROOT or something like that.  If that envvar is set, you're declaring, hey I want to run as root and I'm taking responsibility for it running as root in my config.

**Comment by samedder** [comment]
@bryanmacfarlane sorry I was OOF on vacation.

I see, well I made the suggested changes. I don't know what's the best decision for your product so I'll leave this PR up to you to close if you don't want to support this option.

If we continue to use VSTS agents deployed with this configuration do we increase the risk of running into more issues?

**Pull request merged**
