### PR TITLE
always set port for git proxy uri.

### PR DESCRIPTION
**Pull request by TingluoHuang**

### CODE REVIEW

**Comment by TingluoHuang** [comment]
#670

**Comment by yugmac** [comment]
@TingluoHuang Could you send me the agent for this please?

**Comment by TingluoHuang** [comment]
@yugmac the agent package is too big to send, we will do a releases with it within 1-2 days.

**Comment by yugmac** [comment]
@TingluoHuang What was in the email you sent? I am trying to get the email released from quarantine.

**Comment by TingluoHuang** [comment]
@yugmac  the .dlls build from this branch that contains the changes.

**Comment by yugmac** [comment]
I managed to get it released and arrive into my mailbox! I added the dll into the bin folder along with the other files however this time when running through the config.cmd I get an error message "Could not load type 'Microsoft.TeamFoundation.DistributedTask.WebApi.TaskAgentPoolActionFilter' from assembly 'Microsoft.TeamFoundation.DistributedTask.WebApi, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'." when at the Register Agent stage.

**Comment by TingluoHuang** [comment]
@yugmac let me publish a new release with this fix.

**Comment by yugmac** [comment]
@TingluoHuang Yeah that will be great! Thanks :+1:

**Pull request merged**
