### PR TITLE
Initial changes for Artifact command extensions

### PR DESCRIPTION
**Pull request by dibathoj**

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
I don't understand the point of this PR.  The agent already has artifact command extensions.  Can you outline the need for all this extra code?

**Comment by dibathoj** [comment]
@bryanmacfarlane  This PR is related to build/RM convergence.

**Comment by bryanmacfarlane** [comment]
Please hold.  We are discussing.  The convergence cannot require agent changes.

**Comment by TingluoHuang** [comment]
I don't think we need this change anymore.

**Pull request closed without merging**
