### PR TITLE
Added command to unblock the dlls from external\vstshost folder

### PR DESCRIPTION
**Pull request by chshrikh**

### CODE REVIEW

**Comment by ericsciple** [comment]
Can you change to `Get-ChildItem -LiteralPath '%~dp0externals\vstsom', '%~dp0externals\vstshost'`?  The line is already incredibly difficult to read and that will condense it a bit. I thought about moving it to a separate script before so it's not all jammed into one line... but that script would need to be unblocked before invoking it :)

run.cmd needs the same change

**Comment by chshrikh** [comment]
@ericsciple  sure I will update

**Comment by chshrikh** [comment]
@ericsciple  updated the PR

**Comment by TingluoHuang** [comment]
Looks good.

**Comment by ericsciple** [comment]
Thanks! Can you please squash before merging so history remains useful when tracking down issues?

**Comment by chshrikh** [comment]
closing this PR, something went with local git commits. created new PR - https://github.com/Microsoft/vsts-agent/pull/538 and merged that as per this code review

**Pull request closed without merging**
