### PR TITLE
BugFix 1024672: remove timeout on downloading of files.

### PR DESCRIPTION
**Pull request by omeshp**

### CODE REVIEW

**Comment by TingluoHuang** [comment]
@omeshp what's the default timeout now, 100s?

**Comment by omeshp** [comment]
@TingluoHuang Default timeout is 100s which will be dictated by the FileContainerClient used in the provider.

**Comment by TingluoHuang** [comment]
@omeshp does it means we are reducing timeout from 5 mins to 100 seconds?

**Comment by omesh** [comment]
@TingluoHuang No the connection timeout is still 100 ms which is enforced by FileContainerClient, there is no download timeout for individual files, earlier this was 5 mins.

**Pull request merged**
