### PR TITLE
Users/tihuang/fixtfslfs

### PR DESCRIPTION
**Pull request by TingluoHuang**

### CODE REVIEW

**Comment by Tasteful** [comment]
@TingluoHuang Can you share any artifacts for this PR so I can test and see if that is working for me?

**Comment by TingluoHuang** [comment]
@Tasteful sure, what's your agent version? i can prepare a binary for your agent version.

**Comment by Tasteful** [comment]
@TingluoHuang Using the `vsts-agent-win7-x64-2.120.2.zip` package from the release tab.

**Comment by TingluoHuang** [comment]
@Tasteful 
[Agent.Worker.zip](https://github.com/Microsoft/vsts-agent/files/1249845/Agent.Worker.zip)
replace the `agent.worker.dll` under your agent's `bin` folder.

**Comment by Tasteful** [comment]
@TingluoHuang I have now tested on two environments and the updated dll is working on both of them!
* Win 10 developer machine
* Windows Server 2012r2 (build server)

Is it safe to continue to run on this DLL or should I wait for a new agent release?

**Comment by TingluoHuang** [comment]
@Tasteful those assembly was built from my dev box, so they don't get code signing. as long as you environment doesn't require all binary be digital signed, you should be good to use them.

**Comment by Tasteful** [comment]
:+1: thanks for the fast help

**Pull request merged**
