### PR TITLE
Addding DeploymentJobExtension

### PR DESCRIPTION
**Pull request by KrishnaAdityaB**

### CODE REVIEW

**Comment by KrishnaAdityaB** [comment]
@TingluoHuang @kmkumaran @niadak

**Comment by niadak** [comment]
Looks good

**Comment by TingluoHuang** [comment]
Looks good, @KrishnaAdityaB you want me merge?

**Comment by KrishnaAdityaB** [comment]
@TingluoHuang Yes, please merge this.
And can you tell me - when these changes will reach the prod? And what am I required to do/validate/monitor?
Thanks

**Comment by TingluoHuang** [comment]
@KrishnaAdityaB about a week.

**Pull request merged**
